### ISSUE TITLE
The IDE should handle invalid CLI configuration gracefully

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#100]
Originally from here: https://github.com/arduino/arduino-pro-ide/issues/310

Start your app with such an invalid config and it hangs:
```yaml
board_manager:
  additional_urls:
  https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
daemon:
  port: "50051"
directories:
  data: /Users/akos.kitta/Library/Arduino15
  downloads: /Users/akos.kitta/Library/Arduino15/staging
  user: /Users/akos.kitta/Documents/Arduino
logging:
  file: ""
  format: text
  level: info
telemetry:
  addr: :9090
  enabled: true
```
